ShopTobaccoWebApp.WebUI/Models/CartIndexViewModel.cs
using ShopTobaccoWebApp.Domain.Entities;

namespace ShopTobaccoWebApp.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

ShopTobaccoWebApp.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShopTobaccoWebApp.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

ShopTobaccoWebApp.WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ShopTobaccoWebApp.Domain.Entities;

namespace ShopTobaccoWebApp.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }

        public string SearchProduct { get; set; }
    }
}

ShopTobaccoWebApp.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using ShopTobaccoWebApp.Domain.Entities;
using ShopTobaccoWebApp.Domain.Abstract;
using ShopTobaccoWebApp.WebUI.Models;

namespace ShopTobaccoWebApp.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(g => g.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(g => g.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        //public Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
    }
}

ShopTobaccoWebApp.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopTobaccoWebApp.Domain.Abstract;

namespace ShopTobaccoWebApp.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                                                        .Select(x => x.Category)
                                                        .Distinct()
                                                        .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

ShopTobaccoWebApp.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopTobaccoWebApp.Domain.Abstract;
using ShopTobaccoWebApp.Domain.Entities;
using ShopTobaccoWebApp.WebUI.Models;

namespace ShopTobaccoWebApp.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;

        public int pageSize = 5;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, string searchString, int page = 1)
        {
            var model = new ProductsListViewModel
            {
                Products = repository.Products
                                        .Where(x => category == null || x.Category == category)
                                        .Where(x => searchString == null || x.Name.Contains(searchString))
                                        .OrderBy(x => x.ProductId)
                                        .Skip((page - 1) * pageSize)
                                        .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null && searchString == null?
                        repository.Products.Count() :
                        repository.Products
                        .Where(product => category != null && product.Category == category)
                        .Where(product => searchString != null && product.Name.Contains(searchString))
                        .Count()
                },
                CurrentCategory = category,
                SearchProduct = searchString
            };

            return View(model);
        }
    }
}

ShopTobaccoWebApp.WebUI/Views/Cart/Checkout.cshtml
@model ShopTobaccoWebApp.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Форма заказа";
}

<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введите ваши контактные данные, и скоро мы его отправим!</p>


@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }


    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

ShopTobaccoWebApp.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ создан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

ShopTobaccoWebApp.WebUI/Views/Cart/Index.cshtml
@model ShopTobaccoWebApp.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "ShopTobacco: ваша корзина";
}

<h2>Ваша корзина</h2>

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Кол-во</th>
            <th>Позиция</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("# руб")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("# руб"))
            </td>
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("ProductId", line.Product.ProductId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary" })
</div>

ShopTobaccoWebApp.WebUI/Views/Cart/Summary.cshtml
@model ShopTobaccoWebApp.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Корзина", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) позиций, на сумму
    @Model.ComputeTotalValue().ToString("# руб")
</div>

ShopTobaccoWebApp.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Очистить фильтр", "List", "Product", null,
    new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var categoryFilter in Model)
{
    @Html.RouteLink(categoryFilter, new
    {
        controller = "Product",
        action = "List",
        category = categoryFilter,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg"
            + (categoryFilter == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}

ShopTobaccoWebApp.WebUI/Views/Product/List.cshtml
@using ShopTobaccoWebApp.WebUI.Models
@using ShopTobaccoWebApp.WebUI.HtmlHelpers
@model ProductsListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var product in Model.Products)
{
    @Html.Partial("ProductSummary", product)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

ShopTobaccoWebApp.WebUI/Views/Shared/ProductSummary.cshtml
@model ShopTobaccoWebApp.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Category</span>
</div>

ShopTobaccoWebApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">ShopTobacco</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div>
            @using(Html.BeginForm("List", "Product"))
            {
                <table>
                    <tr>
                        <td>
                            <input type="text" class="form-control" id="searchString" name="searchString" placeholder="Поиск" value="">
                        </td>
                        <td>
                            <input type="submit" class="btn btn" value="Найти" />
                        </td>
                    </tr>
                </table>
            }
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>